export const productsList = [
  {
    name: 'Classic Canvas Sneakers',
    description: 'Comfortable and stylish canvas sneakers for everyday wear.',
    price: 59.99,
    image: 'products/1.png',
    stripePriceId: 'price_xxxxx_sneakers1',
    createdAt: new Date(),
    updatedAt: new Date(),
    isFeatured: false,
  },
  {
    name: 'Premium Leather Sneakers',
    description: 'High-quality leather sneakers with cushioned soles.',
    price: 89.99,
    image: 'products/2.png',
    stripePriceId: 'price_xxxxx_sneakers2',
    isFeatured: true,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    name: 'Retro Running Sneakers',
    description: 'Classic retro-style sneakers for a vintage look.',
    price: 74.99,
    image: 'products/3.png',
    stripePriceId: 'price_xxxxx_sneakers3',
    createdAt: new Date(),
    updatedAt: new Date(),
    isFeatured: false,
  },
  {
    name: 'Athletic Performance Sneakers',
    description: 'Lightweight sneakers designed for sports and training.',
    price: 99.99,
    image: 'products/4.png',
    stripePriceId: 'price_xxxxx_sneakers4',
    createdAt: new Date(),
    updatedAt: new Date(),
    isFeatured: false,
  },
  {
    name: 'Limited Edition Sneakers',
    description: 'Exclusive sneakers featuring unique designs.',
    price: 129.99,
    image: 'products/5.png',
    stripePriceId: 'price_xxxxx_sneakers5',
    createdAt: new Date(),
    updatedAt: new Date(),
    isFeatured: false,
  },
  {
    name: 'Slip-On Sneakers',
    description: 'Convenient slip-on design with elastic side accents.',
    price: 49.99,
    image: 'products/6.png',
    stripePriceId: 'price_xxxxx_sneakers6',
    createdAt: new Date(),
    updatedAt: new Date(),
    isFeatured: true,
  },
  {
    name: 'High-Top Basketball Sneakers',
    description: 'Ankle support sneakers for court performance.',
    price: 119.99,
    image: 'products/7.png',
    stripePriceId: 'price_xxxxx_sneakers7',
    createdAt: new Date(),
    updatedAt: new Date(),
    isFeatured: false,
  },
  {
    name: 'Eco-Friendly Sneakers',
    description: 'Sustainable sneakers made from recycled materials.',
    price: 79.99,
    image: 'products/8.png',
    stripePriceId: 'price_xxxxx_sneakers8',
    createdAt: new Date(),
    updatedAt: new Date(),
    isFeatured: false,
  },
  {
    name: 'Winterized Sneakers',
    description: 'Weather-resistant sneakers for cold conditions.',
    price: 89.99,
    image: 'products/9.png',
    stripePriceId: 'price_xxxxx_sneakers9',
    createdAt: new Date(),
    updatedAt: new Date(),
    isFeatured: false,
  },
  {
    name: 'Minimalist Running Sneakers',
    description: 'Ultra-lightweight sneakers for natural movement.',
    price: 69.99,
    image: 'products/10.png',
    stripePriceId: 'price_xxxxx_sneakers10',
    createdAt: new Date(),
    updatedAt: new Date(),
    isFeatured: true,
  },
];
