export const productsList = [
  {
    name: 'Classic Cotton Hoodie',
    description: 'Soft and comfortable cotton hoodie for everyday wear.',
    price: 39.99,
    image: 'products/1.png',
    stripePriceId: 'price_xxxxx_hoodie1',
    createdAt: new Date(),
    updatedAt: new Date(),
    isFeatured: false,
  },
  {
    name: 'Premium Zip-Up Hoodie',
    description: 'High-quality zip-up hoodie with premium fabric.',
    price: 49.99,
    image: 'products/2.png',
    stripePriceId: 'price_xxxxx_hoodie2',
    isFeatured: true,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    name: 'Oversized Pullover Hoodie',
    description: 'Trendy oversized hoodie for a relaxed fit.',
    price: 44.99,
    image: 'products/3.png',
    stripePriceId: 'price_xxxxx_hoodie3',
    createdAt: new Date(),
    updatedAt: new Date(),
    isFeatured: false,
  },
  {
    name: 'Athletic Performance Hoodie',
    description: 'Breathable hoodie designed for active lifestyles.',
    price: 54.99,
    image: 'products/4.png',
    stripePriceId: 'price_xxxxx_hoodie4',
    createdAt: new Date(),
    updatedAt: new Date(),
    isFeatured: false,
  },
  {
    name: 'Graphic Print Hoodie',
    description: 'Hoodie featuring unique graphic designs.',
    price: 45.99,
    image: 'products/5.png',
    stripePriceId: 'price_xxxxx_hoodie5',
    createdAt: new Date(),
    updatedAt: new Date(),
    isFeatured: false,
  },
  {
    name: 'Basic Crewneck T-Shirt',
    description: 'Classic fit crewneck t-shirt in various colors.',
    price: 19.99,
    image: 'products/t1.png',
    stripePriceId: 'price_xxxxx_tshirt1',
    isFeatured: true,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    name: 'V-Neck Soft Cotton Tee',
    description: 'Comfortable v-neck t-shirt made from premium cotton.',
    price: 22.99,
    image: 'products/t2.png',
    stripePriceId: 'price_xxxxx_tshirt2',
    createdAt: new Date(),
    updatedAt: new Date(),
    isFeatured: false,
  },
  {
    name: 'Graphic Print T-Shirt',
    description: 'Trendy t-shirt with artistic graphic prints.',
    price: 24.99,
    image: 'products/t3.png',
    stripePriceId: 'price_xxxxx_tshirt3',
    createdAt: new Date(),
    updatedAt: new Date(),
    isFeatured: false,
  },
  {
    name: 'Pocket Tee',
    description: 'Classic t-shirt with chest pocket for casual style.',
    price: 21.99,
    image: 'products/t4.png',
    stripePriceId: 'price_xxxxx_tshirt4',
    createdAt: new Date(),
    updatedAt: new Date(),
    isFeatured: false,
  },
  {
    name: 'Long Sleeve T-Shirt',
    description: 'Versatile long sleeve tee for cooler weather.',
    price: 26.99,
    image: 'products/t5.png',
    stripePriceId: 'price_xxxxx_tshirt5',
    createdAt: new Date(),
    updatedAt: new Date(),
    isFeatured: false,
  },
];
